# this file is called by bash when it is run as a login shell,
# and it calls ~/.bashrc, which is called by bash when it is run
# as an interactive non-login shell

if [[ -z "$WORKHOME" ]]; then
	WORKHOME="$HOME"
	export WORKHOME
fi

if [ -f "$WORKHOME/.bashrc" ]; then . "$WORKHOME/.bashrc"; fi

# treat .profile as host-specific settings
if [ -f "$WORKHOME/.profile" ]; then . "$WORKHOME/.profile"; fi

export BASH_SILENCE_DEPRECATION_WARNING=1

ARM_BREW=/opt/homebrew/bin/brew
if [ -e "$ARM_BREW" ]; then
	eval "$($ARM_BREW shellenv)"
elif command -v brew >/dev/null ; then
	eval "$(brew shellenv)"
fi

