# this file is called by bash when it is run as a login shell,
# and it calls ~/.bashrc, which is called by bash when it is run
# as an interactive non-login shell

if [[ -z "$WORKHOME" ]]; then
	WORKHOME="$HOME"
	export WORKHOME
fi

if [ -f "$WORKHOME/.bashrc" ]; then . "$WORKHOME/.bashrc"; fi

# treat .profile as host-specific settings
if [ -f "$WORKHOME/.profile" ]; then . "$WORKHOME/.profile"; fi

export BASH_SILENCE_DEPRECATION_WARNING=1


# Created by `pipx` on 2024-07-23 21:20:31
export PATH="$PATH:/Users/narthur/.local/bin"
if [ -f "$HOME/.cargo/env" ]; then
	. "$HOME/.cargo/env"
fi
