#!/bin/sh

if [ "x$1x" = "xx" ]; then
	echo "args: <path/to/apache/access/log/file> <arbitrary string (e.g. your IP address) to exclude from results>"
	exit 0;
fi
sitestats $1 $2 - | \

#awk '{print $1}' $1 | sort | uniq -c | sort | tail -n 50 |   \
while read line
do
	set -- $line
	echo -n $1
	echo -n " "
	echo -n $2
	echo -n " "
	echo `dnsname $2`
done
