#!/bin/sh

set -e

if [ -z "$1" ]; then
        echo "usage: $0 <session-name>" 1>&2
        exit 1
fi

if tmux has-session -t $1; then
        tmux attach-session -d -t $1
else
        cd
        tmux new-session -s $1
fi

exit $?

