#!/usr/bin/env bash

set -e

if [ "-s" == "$1" ]; then
	SEARCH_ONLY=1
	shift
fi

if [ -z "$1" ]; then
	echo "Must specify a file from within the current git repo" 1>&2
	exit 1;
fi

CDP_ARGS_WORKAROUND=("$@")
set --
# another utility script that must be in the path
. `which cdp`
set -- "${CDP_ARGS_WORKAROUND[@]}"

file_list=()
while [ -n "$1" ]; do
	SEEK="$1"
	shift

	FIND_COMMAND='find . -path "./.git" -prune -o -type f -path "*$SEEK*" -print0'

	while IFS= read -d $'\0' -r file ; do
		file_list=("${file_list[@]}" "$file")
	done < <(eval ${FIND_COMMAND})
done

if [ "1" == "$SEARCH_ONLY" ]; then
	printf '%s\n' "${file_list[@]}"
	exit 0;
elif [ -f $SEEK ]; then
	FOUND=$SEEK
else
	if [ -z "${file_list[*]}" ]; then
		echo "Can't find '$SEEK' or '`pwd`/$SEEK' or anything matching '*$SEEK*' in '`pwd`'" 1>&2
		exit 2;
	fi
fi

printf '%s\n' "${file_list[@]}"
$EDITOR -o "${file_list[@]}" $SECOND_FILE

