#!/bin/sh

set -e

mkdir -p ~/.vim/bundle
cd ~/.vim/bundle/

clone_or_update() {
	AUTH=$1
	NAME=$2

	echo "\n$AUTH/$NAME"
	if [ ! -e $NAME ]; then
		git clone https://github.com/$AUTH/${NAME}.git
	else
		cd $NAME
		git pull
		cd - >/dev/null
	fi
}

# this powers the rest
clone_or_update 'tpope' 'vim-pathogen'

# odds 'n ends
clone_or_update 'airblade' 'vim-gitgutter'
clone_or_update 'plasticboy' 'vim-markdown'
clone_or_update 'vim-scripts' 'ikiwiki-syntax'
clone_or_update 'ervandew' 'supertab'
clone_or_update 'PProvost' 'vim-ps1'
clone_or_update 'blueyed' 'vim-autoclose'
clone_or_update 'ntpeters' 'vim-better-whitespace'
clone_or_update 'vim-airline' 'vim-airline'
clone_or_update 'weynhamz' 'vim-plugin-minibufexpl'
clone_or_update 'maxbrunsfeld' 'vim-yankstack'

# search for files
#clone_or_update 'rking' 'ag.vim'
#clone_or_update 'Chun-Yang' 'vim-action-ag'
clone_or_update 'ctrlpvim' 'ctrlp.vim'

# tpope
clone_or_update 'tpope' 'vim-commentary'
clone_or_update 'tpope' 'vim-endwise'
clone_or_update 'tpope' 'vim-flagship'
clone_or_update 'tpope' 'vim-fugitive'
clone_or_update 'tpope' 'vim-repeat'
clone_or_update 'tpope' 'vim-surround'
clone_or_update 'tpope' 'vim-unimpaired'
clone_or_update 'tpope' 'vim-vinegar'

# truist
clone_or_update 'truist' 'vim-open-url'


cd - >/dev/null

