#!/bin/sh

set -e

mkdir -p ~/.vim/bundle
cd ~/.vim/bundle/

git clone https://github.com/tpope/vim-pathogen.git

git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/plasticboy/vim-markdown.git
git clone https://github.com/vim-scripts/ikiwiki-syntax
git clone https://github.com/ervandew/supertab.git
git clone https://github.com/PProvost/vim-ps1.git
git clone https://github.com/tpope/vim-surround.git

cd -

