#!/usr/bin/env bash

set -e

if [[ -n "$1" ]]; then
	WORKHOME="$1"
	if [ ! -d "$WORKHOME" ]; then
		echo "$WORKHOME must be a directory" >&2
		echo "args: [<path/to/new/working home directory>]"
		exit 1
	fi
else
	WORKHOME="$HOME"
fi

mkdir -p "$WORKHOME/.vim/bundle"
cd "$WORKHOME/.vim/bundle/"

clone_or_update() {
	AUTH=$1
	NAME=$2

	printf '\n%s/%s\n' "$AUTH" "$NAME"
	if [ ! -e "$NAME" ]; then
		git clone "https://github.com/$AUTH/${NAME}.git"
	else
		cd "$NAME"
		git pull
		cd - >/dev/null
	fi
}

# this powers the rest
clone_or_update 'tpope' 'vim-pathogen'

# tpope
clone_or_update 'tpope' 'vim-commentary'
clone_or_update 'tpope' 'vim-endwise'
clone_or_update 'tpope' 'vim-flagship'
clone_or_update 'tpope' 'vim-fugitive'
clone_or_update 'tpope' 'vim-repeat'
clone_or_update 'tpope' 'vim-surround'
clone_or_update 'tpope' 'vim-unimpaired'
clone_or_update 'tpope' 'vim-vinegar'

# odds 'n ends
clone_or_update 'ConradIrwin' 'vim-bracketed-paste'
#clone_or_update 'PProvost' 'vim-ps1'
clone_or_update 'airblade' 'vim-gitgutter'
#clone_or_update 'blueyed' 'vim-autoclose'
clone_or_update 'cohama' 'lexima.vim'
clone_or_update 'ctrlpvim' 'ctrlp.vim'
clone_or_update 'dense-analysis' 'ale'
#clone_or_update 'dhruvasagar' 'vim-table-mode'
clone_or_update 'editorconfig' 'editorconfig-vim'
clone_or_update 'ervandew' 'supertab'
clone_or_update 'itspriddle' 'vim-shellcheck'
#clone_or_update 'maxbrunsfeld' 'vim-yankstack'
clone_or_update 'ntpeters' 'vim-better-whitespace'
#clone_or_update 'plasticboy' 'vim-markdown'
clone_or_update 'rust-lang' 'rust.vim'
clone_or_update 'vim-airline' 'vim-airline'
clone_or_update 'vim-airline' 'vim-airline-themes'
#clone_or_update 'vim-scripts' 'ikiwiki-syntax'
clone_or_update 'weynhamz' 'vim-plugin-minibufexpl'

# truist
#clone_or_update 'truist' 'vim-open-url'

